ShopQuanAo/ShopQuanAo/Areas/admin/Controllers/SlidesController.cs
using Models.DAL;
using Models.EntityFramework;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopQuanAo.Areas.admin.Controllers
{
    public class SlidesController : BaseController
    {
        // GET: admin/Slides
        private DAL_Slides DalSlides { get; set; }
        public SlidesController()
        {
            this.DalSlides = new DAL_Slides();
        }
        public ActionResult Index(int? page)
        {
            int pagenumber = (page ?? 1) - 1;
            int totalCount = 0;
            var listSlides = this.DalSlides.GetPageSlides(pagenumber, 10, out totalCount);
            IPagedList<SLIDE> pageOrders = new StaticPagedList<SLIDE>(listSlides, pagenumber + 1, 10, totalCount);
            return View(pageOrders);
        }

        // GET: admin/Slides/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: admin/Slides/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Slides/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "TIEU_DE , LINK , STT")] SLIDE slides)
        {
            try
            {
                var sql = "Select * from SLIDE where TIEU_DE = N'" + slides.TIEU_DE + "';";
                var check = this.DalSlides.sqlQueryFristOrDefault(sql);
                if (ModelState.IsValid && check==false)
                { 
                    if(Request.Files.Get("images").ContentLength == 0)
                    {
                        ViewBag.Err = "Images không được để trống !!!";
                        return View(slides);
                    }
                    else
                    {
                        slides.IMAGES = SaveUploadImage(Request.Files.Get("images"));
                    }
                    if (Request.Form["is_active"] != null)
                    {
                        slides.TRANG_THAI = Boolean.Parse(Request.Form["is_active"]);
                    }
                    else
                    {
                        slides.TRANG_THAI = false;
                    }
                    if (!this.DalSlides.InsertSlides(slides))
                    {
                        ViewBag.Err = "Lỗi không thể chèn Slides !!!";
                        return View(slides);
                    }
                    else
                    {
                        ViewBag.Success = "Chèn Thành Công !!!";
                        return RedirectToAction("Index");
                    }
                    
                }
                // TODO: Add insert logic here
                else
                {
                    ViewBag.Err = "Tiêu đề Slides đã tồn tại";
                    return View(slides);
                }
            }
            catch
            {
                return View(slides);
            }
        }


        public string SaveUploadImage(HttpPostedFileBase file)
        {
            var str_file = "";
            Random random = new Random();
            if (file != null && file.ContentLength > 0)
            {
                //Định nghĩa đường dẫn lưu file trên server
                var ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + file.FileName);
                string newFileName = file.FileName;
                //lấy đường dẫn lưu file sau khi kiểm tra tên file trên server có tồn tại hay không
                while (System.IO.File.Exists(ServerSavePath) == true)
                {
                    string filename = Path.GetFileNameWithoutExtension(newFileName);
                    string extension = Path.GetExtension(newFileName);
                    newFileName = filename + "_" + random.Next(1, 1000) + extension;
                    ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + newFileName);
                }
                //Lưu hình ảnh Resize từ file sử dụng file.InputStream
                file.SaveAs(ServerSavePath);

                str_file = "/UploadFileImage/images/" + newFileName;
            }
            return str_file;// trả về đường dẫn file trong thư mục
        }

        // GET: admin/Slides/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SLIDE slide = this.DalSlides.returnSlides(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            
            return View(slide);
        }

        // POST: admin/Slides/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ID , TIEU_DE , LINK , STT")] SLIDE slides)
        {
            try
            {
                var sql = "Select * from SLIDE where id!='"+slides.ID+"' and  TIEU_DE = N'" + slides.TIEU_DE + "';";
                bool check = DalSlides.sqlQueryFristOrDefault(sql);
                if (Request.Form["is_active"] != null)
                {
                    slides.TRANG_THAI = Boolean.Parse(Request.Form["is_active"]);
                }
                if (ModelState.IsValid && check == false)
                {
                    if (Request.Files.Get("images").ContentLength == 0)
                    {
                        slides.IMAGES = this.DalSlides.returnSlides(slides.ID).IMAGES;
                    }
                    else
                    {
                        slides.IMAGES = SaveUploadImage(Request.Files.Get("images"));
                    }
                    if (!this.DalSlides.EditSlides(slides.ID , slides))
                    {
                        ViewBag.Err = "Lỗi không thể chèn Slides !!!";
                        return View(slides);
                    }
                    else
                    {
                        ViewBag.Success = "Sửa Thành Công !!!";
                        return RedirectToAction("Index");
                    }

                }
                // TODO: Add insert logic here
                else
                {
                    ViewBag.Err = "Tiêu đề Slides đã tồn tại";
                    return View(slides);
                }
            }
            catch
            {
                return View(slides);
            }
        }

        // GET: admin/Slides/Delete/5
        public ActionResult Delete(int id)
        {
            var result = new DAL_Slides().DeleteSlide(id);

            return Json(new
            {
                status = (result) ? "success" : "error",
            }, JsonRequestBehavior.AllowGet);
        }

        // POST: admin/Slides/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ShopQuanAo/ShopQuanAo/Areas/admin/Views/Slides/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
@model Models.EntityFramework.SLIDE
@section jsFooter{
    
    <script src="~/Public/admin/js/slide.js"></script>
}

<div class="section__content section__content--p30 mt-3">
    <div class="container-fluid">
        <div class="row ml-0 mr-0">
            @using (Html.BeginForm("Create", "Slides", FormMethod.Post, new { @class = "w-100", @enctype = "multipart/form-data" }))
            {

                @Html.AntiForgeryToken()

                <div class="card w-100">
                    <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                        <h3><strong>Thêm </strong> Slides</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <p>
                            @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                        </p>
                    </div>
                    <div class="card-body card-block">
                        @if (ViewBag.Err != null)
                        {
                            <div class="alert alert-danger">
                                <strong>Error : !</strong> @ViewBag.Err
                            </div>
                        }
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Tiêu Đề :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.TIEU_DE, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                                @Html.ValidationMessageFor(model => model.TIEU_DE, "", new { @class = "help-block form-text text-danger" })


                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Link :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.LINK, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK, "", new { @class = "help-block form-text text-danger" })
                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">STT</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.STT, new { htmlAttributes = new { @type = "number", @value = "0", @min = "0", @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Ảnh Chính</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <div class="form-group ">
                                    <input type="file" name="images" id="images" class="file-upload-default-image" style="position: absolute ; visibility: hidden;">
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">

                                        <span class="input-group-append">
                                            <button class="file-upload-image btn btn-primary" type="button">Upload</button>
                                        </span>
                                    </div>
                                    <small class="validate validate-images text-danger form-text "></small>
                                    <div class="hien-thi-image-chinh" style="min-width: 400px; max-width:500px ; margin: 1rem auto;">

                                    </div>
                                </div>

                            </div>
                            <div class="col-12">

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Hiển thị :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="checkbox" name="is_active" value="true"/>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </div>
            }



        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

ShopQuanAo/ShopQuanAo/Areas/admin/Views/Slides/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@model Models.EntityFramework.SLIDE
@section jsFooter{

    <script src="~/Public/admin/js/slide.js"></script>
}

<div class="section__content section__content--p30 mt-3">
    <div class="container-fluid">
        <div class="row ml-0 mr-0">
            @using (Html.BeginForm("Edit", "Slides", FormMethod.Post, new { @class = "w-100", @enctype = "multipart/form-data" }))
            {

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID)
                <div class="card w-100">
                    <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                        <h3><strong>Thêm </strong> Slides</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <p>
                            @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                        </p>
                    </div>
                    <div class="card-body card-block">
                        @if (ViewBag.Err != null)
                        {
                            <div class="alert alert-danger">
                                <strong>Error : !</strong> @ViewBag.Err
                            </div>
                        }
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Tiêu Đề :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.TIEU_DE, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                                @Html.ValidationMessageFor(model => model.TIEU_DE, "", new { @class = "help-block form-text text-danger" })


                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Link :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.LINK, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK, "", new { @class = "help-block form-text text-danger" })
                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">STT</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.STT, new { htmlAttributes = new { @type = "number", @value = "0", @min = "0", @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Ảnh Chính</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <div class="form-group ">
                                    <input type="file" name="images" id="images" class="file-upload-default-image" style="position: absolute ; visibility: hidden;">
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">

                                        <span class="input-group-append">
                                            <button class="file-upload-image btn btn-primary" type="button">Upload</button>
                                        </span>
                                    </div>
                                    <small class="validate validate-images text-danger form-text "></small>
                                    <div class="hien-thi-image-chinh" style="min-width: 400px; max-width:500px ; margin: 1rem auto;">
                                        <img class="w-100 h-100" src="@Model.IMAGES" />
                                    </div>
                                </div>

                            </div>
                            <div class="col-12">

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Hiển thị :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="checkbox" name="is_active" value="true" @(Model.TRANG_THAI.Value ? "checked":"") />
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </div>
            }



        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

ShopQuanAo/ShopQuanAo/Areas/admin/Views/Slides/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@model PagedList.IPagedList<Models.EntityFramework.SLIDE>

@using PagedList.Mvc;


@section jsFooter{
    <script>
        $(".btn-delete-slide").off("click").on("click", function (e) {
            e.preventDefault();
            var btn = $(this);
            var id = btn.data("id");
            console.log(id);
            Swal.fire({
                title: 'Delete',
                icon: 'error',
                showCancelButton: true,
                confirmButtonText: 'Có',
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    $.ajax({
                        url: '/admin/Slides/Delete/' + id,
                        dataType: 'json',
                        type: "get"
                    }).done(function (data) {
                        // If successful
                        if (data.status == "success") {
                            Swal.fire("", "", data.status);
                            var row = $(".table-lsp").children("tbody").find("tr#row_" + id);
                            row.remove();
                        } else {
                            Swal.fire("", "", data.status);
                        }
                    })
                }
            });
        });
    </script>
}
@section cssHeader{

    <style>
        ul.pagination {
            justify-content: center;
        }

            ul.pagination li {
                display: inline;
                background: #e9ecef;
            }

                ul.pagination li.active {
                    background: teal;
                    color: white;
                }

                ul.pagination li a {
                    color: black;
                    float: left;
                    padding: 8px 16px;
                    text-decoration: none;
                    font-size: 16px;
                    transition: background-color .3s;
                }

                    ul.pagination li a.active {
                        background: teal;
                        color: white;
                    }

                    ul.pagination li a:hover:not(.active) {
                        background-color: #ddd;
                    }
    </style>

}



<div class="d-flex pl-3 pr-3 justify-content-between align-items-center mb-3">
    <h3 class="">Danh Sách Loại Sản Phẩm</h3>

    <p>
        @Html.ActionLink("Thêm Mới", "Create", null, new { @class = "btn btn-success" })
    </p>
</div>
<div class="section__content section__content--p30">

    <div class="container-fluid">
        <div class="row m-t-3">
            <div class="col-md-12">
                <!-- DATA TABLE-->
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success">
                        <strong>Success : !</strong>@ViewBag.Success
                    </div>
                }

                <div class="table-responsive m-b-40" style=" position:relative;">
                    <table class="table table-borderless table-data3 table-lsp">

                        <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th>Tiêu Đề</th>
                                <th>Ảnh</th>
                                <th>Link</th>
                                <th>STT</th>
                                <th>Ngày Tạo</th>
                                <th>Status</th>
                                <th width="5%"></th>
                            </tr>
                        </thead>
                        <tbody>


                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">
                                    <td> @Html.DisplayFor(modelItem => item.ID)</td>
                                    <td> @Html.DisplayFor(modelItem => item.TIEU_DE)</td>
                                    <td> <img src="@item.IMAGES" style="max-width:200px; max-height:100px;" alt="Alternate Text" /></td>
                                    <td> @Html.DisplayFor(modelItem => item.LINK)</td>
                                    <td> @Html.DisplayFor(modelItem => item.STT)</td>
                                    <td> @Html.DisplayFor(modelItem => item.NGAY_DANG)</td>
                                    <td class="process">

                                        <span data-id="@item.ID" class="badge badge-pill  @((item.TRANG_THAI == true)?"badge bg-success":"badge bg-danger")">
                                            <i class="fa  @((item.TRANG_THAI == true)?"fa-eye":"fa-eye-slash")">@((item.TRANG_THAI == true)? "  Active" : "  Die")</i>
                                        </span>


                                    </td>
                                    <td>
                                        <div class="table-data-feature">

                                            <a href="@Url.Action("Edit", "Slides", new { id = item.ID })" class="btn item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                                <i class="zmdi zmdi-edit"></i>
                                            </a>

                                            <a class="btn item btn-delete-slide" data-toggle="tooltip" data-id="@item.ID" data-placement="top" title="" data-original-title="Delete">
                                                <i class="zmdi zmdi-delete"></i>
                                            </a>

                                        </div>
                                    </td>
                                </tr>
                            }



                            <tr>
                                <td colspan="8" class="align-items-center">
                                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
                               {
                                   DisplayLinkToIndividualPages = true,
                                   DisplayPageCountAndCurrentLocation = false,
                                   MaximumPageNumbersToDisplay = 10,
                                   LiElementClasses = new string[] { "page-item" }
                               })
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- END DATA TABLE-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>